/* Generated by myoptions.h generator - v0.9.0 */
/* https://trip5.github.io/ehRadio_myoptions/generator.html */
/* https://github.com/SimZs/yoRadio-Fusion */

/* esp32-S3-devkit-C1 44 pins https://randomnerdtutorials.com/esp32-s3-devkitc-pinout-guide */

/* HSPI (SPI 2) GPIO 11 - MOSI, GPIO 12 - CLK, GPIO 13 - MISO, GPIO 10 - CS */

#pragma once

#ifndef ARDUINO_ESP32S3_DEV
    #define ARDUINO_ESP32S3_DEV
#endif

#define LANGUAGE EN // HU NL PL RU EN EL Enter your own language here!!
#define NAMEDAYS_FILE PL // HU, PL, NL
#define CLOCK_TTS_LANGUAGE "en" //Default language TTS e.g. pl,en,de,ru,fr,hu
// #define IMPERIALUNIT // English weather: Fahrenheit, inHg and mph (requires LANGUAGE EN)

// --- DLNA / Synology ---
//#define USE_DLNA
//#define dlnaHost "192.168.180.122"
//#define dlnaIDX  21

//#define LEDSTRIP_PIN        48

//#define RSSI_DIGIT       true

/******************************************/
// #define LED_BUILTIN_S3    48     /* S3-onboard RGB led pin */
//#define USE_BUILTIN_LED false /* The RGB LED does not turn on.. */
/*****************************************/
//#define DSP_MODEL DSP_ILI9486
//#define DSP_MODEL DSP_ILI9488
#define DSP_MODEL DSP_ILI9341
//#define DSP_MODEL DSP_ST7735
//#define DSP_MODEL DSP_ST7789_76
//#define DSP_MODEL DSP_1602I2C    //2x16 
//#define DSP_MODEL DSP_2004I2C   //4x20
//#define DSP_MODEL DSP_ST7796
//#define DSP_MODEL DSP_SH1106
//#define SH1106_GRAYSCALE  true
//#define DSP_MODEL DSP_SSD1306
//#define DSP_MODEL DSP_GC9A01A
//#define HUN_LCD
/*****************************************/

#define TFT_DC 9
#define TFT_CS 10
#define TFT_RST -1
#define TFT_SCK   12
#define TFT_MOSI  11
//#define TFT_MISO  13

#define BRIGHTNESS_PIN 14
/*****************************************/
// #define NEXTION_RX      15
// #define NEXTION_TX     16
/*****************************************/
/* Touch panel
 Resistive */
/*#define TS_MODEL TS_MODEL_XPT2046
#define TS_CS 42*/
/* Capacitive*/
//#define TS_MODEL TS_MODEL_FT6X36
//#define TS_MODEL TS_MODEL_GT911
//#define TS_SDA 8
//#define TS_SCL 9
//#define TS_RST 42
//#define TS_INT 41
/*****************************************/
/* SD CARD */
//#define SDC_CS    39
//#define SD_SPIPINS 12, 13, 11, SDC_CS  // SCK, MISO, MOSI, CS
//#define SDSPISPEED     4000000 /* 4MHz - Slower speed to prevent display flicker on shared SPI bus */
/****************************************/
/*  I2S DAC  */

/* PCM5102A  DAC */
#define I2S_DOUT 17
#define I2S_BCLK 18
#define I2S_LRC  8

/* ENCODER 1 */
#define ENC_BTNR 5 // S2
#define ENC_BTNL 6 // S1
#define ENC_BTNB 4 // KEY
#define ENC_INTERNALPULLUP		true

#define USE_LASTFM_COVER
#define LASTFM_API_KEY ""
 
/* ENCODER 2 */
/*#define ENC2_BTNR 7 // S2
//#define ENC2_BTNL 16 // S1
//#define ENC2_BTNB 15 // KEY
//#define ENC2_INTERNALPULLUP		true*/

/* BLUETOOTH MODUL (QCC5124EL, AT parancskészlet) */
// Comment out to build FusionEdge without the QCC Bluetooth module.
//#define USE_BLUETOOTH

//#define BT_UART_TX   45   // ESP32 TX -> modul RX
//#define BT_UART_RX   46   // ESP32 RX <- modul TX
//#define BT_UART_BAUD 115200

//#define BT_I2S_BCK   7    // modul I2S BCK  (volt ENC2_BTNR)
//#define BT_I2S_LRCK  15   // modul I2S LRCK (volt ENC2_BTNB)
//#define BT_I2S_DATA  16   // modul I2S DATA (volt ENC2_BTNL)
/********************************************/

/* ÓRA MODUL RTC DS3132 */
// #define RTC_SCL     9
// #define RTC_SDA     8
// #define RTC_MODULE DS3231
/********************************************/

/* REMOTE CONTROL INFRARED RECEIVER */
//#define IR_PIN 17
//#define WAKE_PIN1      1
//#define WAKE_PIN2      17

/********************************************/

/********************************************/
/*  Egyéb beállítások.  */
//#define HAS_PLAYMODE_STATION_WIDGET
#define EXT_WEATHER  true
//#define MUTE_PIN     2            /*  MUTE Pin */
//#define MUTE_VAL    LOW          /*  Write this to MUTE_PIN when player is stop */
//#define PLAYER_FORCE_MONO false  /*  mono option on boot - false stereo, true mono. "false" */
#define I2S_INTERNAL    false    /*  If true - use esp32 internal DAC. "false" */
//#define ROTATE_90   false        /*  Optional 90 degree rotation for square displays."false"*/
//#define TFT_ROTATE      0        /*  Display rotation. 0 - 0, 1 - 90, 2 - 180, 3 - 270 degrees */
//#define HIDE_VOLPAGE             /* Hangerő elrejtés, navigálj a hangerő folyamatjelző sávjával.*/
//#define LIGHT_SENSOR      40               /*  Light sensor  */
//#define AUTOBACKLIGHT(x)  *function*        /*  Autobacklight function. See options.h for example  */
//#define NAME_STRIM              /* Az állomás nevének megjelenítése a streamből. (MOD Maleksm)*/

//#define DOWN_LEVEL           2      /* lowest level brightness (from 0 to 255) */
//#define DOWN_INTERVAL        60     /* interval for BacklightDown in sec (60 sec = 1 min) */
/* ***************************************** */

