#ifndef COMMON_H
#define COMMON_H
#pragma once
#include <stdint.h>

enum displayMode_e { PLAYER, VOL, STATIONS, PRESETS, NUMBERS, LOST, UPDATING, INFO, SETTINGS, TIMEZONE, WIFI, CLEAR, SLEEPING, SDCHANGE, SCREENSAVER, SCREENBLANK, MODESELECT }; // "presets"
enum pages_e      : uint8_t  { PG_PLAYER=0, PG_DIALOG=1, PG_PLAYLIST=2, PG_SCREENSAVER=3, PG_PRESETS=4  }; // "presets"

enum displayRequestType_e { BOOTSTRING, NEWMODE, CLOCK, NEWTITLE, NEWSTATION, NEXTSTATION, DRAWPLAYLIST, CLOSEPLAYLIST, DRAWVOL, DBITRATE, AUDIOINFO, SHOWVUMETER, SWITCHVUMODE, DSPRSSI, SHOWWEATHER, NEWWEATHER, PSTOP, PSTART, DSP_START, WAITFORSD, SDFILEINDEX, NEWIP, NOPE, SHOWRSSIMODE, INVALIDATETHEMEWIDGETS, DRAWMODESELECT, PLAYERREBUILD, NEWCOVER};
struct requestParams_t
{
  displayRequestType_e type;
  int payload;
  uint16_t generation;
};

enum controlEvt_e { EVT_NONE=255, EVT_BTNLEFT=0, EVT_BTNCENTER=1, EVT_BTNRIGHT=2, EVT_ENCBTNB=3, EVT_BTNUP=4, EVT_BTNDOWN=5, EVT_ENC2BTNB=6, EVT_BTNMODE=7 };



#endif
